"""film & genre tables

Revision ID: 49629fa35ba8
Revises: 
Create Date: 2020-11-30 15:59:55.741825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49629fa35ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_genre'), 'genre', ['genre'], unique=True)
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('director', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_film_director'), 'film', ['director'], unique=True)
    op.create_index(op.f('ix_film_name'), 'film', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_name'), table_name='film')
    op.drop_index(op.f('ix_film_director'), table_name='film')
    op.drop_table('film')
    op.drop_index(op.f('ix_genre_genre'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
